# kind -- DaemonSet or Deployment
kind: DaemonSet

# replicaCount -- Only applicable if kind=Deployment
replicaCount: 1

image:
  repository: ghcr.io/axoflow/syslog-ng
  pullPolicy: IfNotPresent
  tag: "4.1.1"  

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config: |
  @version: 4.1
  @include "scl.conf"

  options {
    stats(
      level(1)
    );
  };

  source s_kubernetes {
    kubernetes();
  };

  destination d_local { # TODO: where should we send our logs?
    file("/tmp/out.log");
  };

  log {
    source(s_kubernetes);
    destination(d_local);
  };

# TODO: kubernetes src should have a toggle
# TODO: syslog-ng-ctl healthcheck should be called somewhere

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: {}
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

labels: {}

annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

podLabels: {}

updateStrategy: {}
#   type: RollingUpdate
#   rollingUpdate:
#     maxUnavailable: 1
